### ISSUE TITLE
In beta version it asks to downgrade to production version

### ISSUE THREAD

**Issue by ibu2710** [robohorse/gpversionchecker#10]
In beta version it checks for the version and also show to update to lower production version. please check

**Comment by robohorse** [comment]
ok thanks, i will see it

**Comment by ibu2710** [comment]
Thank you.. Please do it as quick as possible.

**Comment by robohorse** [comment]
I think, that i cant fix it because i cant parse your beta version number (that does not shown on the app page). This library works fine for production version of usual user, but have problems with test cases like yours.
