### ISSUE TITLE
cannot resolve GPVersionChecker

### ISSUE THREAD

**Issue by AbdeenM** [robohorse/gpversionchecker#11]

**Comment by O-liverQueen** [comment]
What I did is,
I imported project as a module (New->File->import module) and used the library, open BuildVariants in android studio from bottom left corner, change build variant to release from debug for both, app and gpversionchecker. Goto Build menu click on generate signed apk, and do the rest.

This procedure works for me.

your question,
(am not sure will this work even though I didn't upload the apk to google play?)
answer
It will work if you don't upload apk without this library to play store.

**Comment by AbdeenM** [comment]
Thank you very much @O-liverQueen, I managed to use a different respo cause I couldn't get this one to work on time.
I really appreciate your answer. I will be using it on my next update.

Cheers!
