### ISSUE TITLE
VersionInfoListener is not fired when app is not found on the Store

### ISSUE THREAD

**Issue by draskosaric** [robohorse/gpversionchecker#12]
This step covers something that, in my opinion, needs to be processed, since I would like to handle this situation in code before publishing the app. 

In that case, I suggest that `VersionInfoListener` should have another method called `onFailure` with or without providing some error code, you decide.

Best,

Drasko

**Comment by robohorse** [comment]
compile 'com.robohorse.gpversionchecker:gpversionchecker:1.2.0'

**Comment by robohorse** [comment]
I added  void onErrorHandled(Throwable throwable);
in VersionInfoListener class
