### ISSUE TITLE
Character encoding problem

### ISSUE THREAD

**Issue by furflez** [robohorse/gpversionchecker#3]
I found some problems with changes text when it has chars like: ç, á, ã, and others with accentuation. Here in Brazil, portuguese language, is very common the use of this chars.

**Comment by robohorse** [comment]
Ok, thanks - i will fix it

**Comment by robohorse** [comment]
Done.
Please change dependency to

``` gradle
compile 'com.robohorse.gpversionchecker:gpversionchecker:1.0.4'
```
