### ISSUE TITLE
java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by PhoebeHB** [robohorse/gpversionchecker#34]
Hi! I'm trying to install this on my app, however, I get this error upon running. There is a large chance that I just made a mistake in the installing process but I ran through your documentation and couldn't see anything. The app is on Google Play and the version code and version name is higher on the store than on the code I am testing. Do you know a solution? Thanks!

<img width="983" alt="Screenshot 2020-06-18 at 16 10 18" src="https://user-images.githubusercontent.com/66947182/85038195-37e56e80-b17e-11ea-88f1-74542f52aeb0.png">

**Comment by VadimSchenev** [comment]
Hi. Could you please provide url of your App? I think, that it can happen, because your app has no version code on google play page. It is normal if you have A/B test, different app versions for different devices... etc. This library cant support this case, sorry (

**Comment by PhoebeHB** [comment]
I think it must be the different versions for different devices, as that is what my app says. Thank you!
