### ISSUE TITLE
Dialog Cancelable 

### ISSUE THREAD

**Issue by surensth** [robohorse/gpversionchecker#35]
The alert dialog need to have cancelable or non cancelable set dynamically as per needs. Better if it would have option to set in builder. Thanks.

**Comment by robohorse** [comment]
Hi, thanks for this message. To show the custom dialog with cancelable option you can use the following configuration: 

```java
 new GPVersionChecker.Builder(this)
                .setVersionInfoListener(new VersionInfoListener() {
                   
                    @Override
                    public void onResulted(Version version) {
                        
                    }
                })
                .create();
```
