### ISSUE TITLE
customized the check url

### ISSUE THREAD

**Issue by jjhesk** [robohorse/gpversionchecker#4]
is this possible to make it enable to support to check the specific url for the version number?

given my own URL: http://xxx.xxx.com/latest.json

``` json
{
"version":"1.2.343"
}

```

**Comment by robohorse** [comment]
No, sorry. You can make your own library, wich will support this.

Just compare 

``` java
final String currentVersion = context.getPackageManager().getPackageInfo(packageName, 0).versionName;
```

with value from your JSON object, obtained by using asynchronous request (RxJava, Thread, AsyncTask... etc.). I recommend to using [Gson](https://github.com/google/gson) and this site [jsonschema2pojo](http://www.jsonschema2pojo.org/) to simplify data obtaining process.
