### ISSUE TITLE
Build issue on Jitpack

### ISSUE THREAD

**Issue by Emeritus-DarranKelinske** [robohorse/gpversionchecker#7]
https://jitpack.io/com/github/robohorse/gpversionchecker/1.0.7/build.log

**Comment by robohorse** [comment]
> Minimum supported Gradle version is 2.14.1.  Current version is 2.7. If using the gradle wrapper, try editing the distributionUrl in /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties to gradle-2.14.1-all.zip

Can you check your gradle-wrapper.properties file?

> /home/jitpack/build/gradle/wrapper/gradle-wrapper.properties

Please check it here

**Comment by dazza5000** [comment]
This is coming from the jitpack build log. I think it is a jitpack setting: https://jitpack.io/#robohorse/gpversionchecker

**Comment by robohorse** [comment]
Ok, i will try to build with jitpack on this saturday/sunday. I hope to find the root of issue

**Comment by dazza5000** [comment]
Thank you Vadim! I'm not sure how jitpack works, but wanted to make sure
you knew it wasn't coming from my personal machine! Thank you!

**Comment by robohorse** [comment]
done

**Comment by robohorse** [comment]
i organized project structure and added jitpack support
